name: Test Vuejs app
on: push

jobs:
  build:
    name: Test on node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          version: '12.x'

      - name: yarn install
        run: |
          yarn install
